- docs/requirements.txt
nnabla-nas document builder fails due to sphinx version mismatch, so fix the sphinx version.
> fix doc build error

- nnabla_nas/contrib/classification/darts/helper.py
- nnabla_nas/contrib/classification/darts/network.py
- nnabla_nas/contrib/classification/fairnas/network.py
- nnabla_nas/contrib/classification/mobilenet/helper.py
- nnabla_nas/contrib/classification/mobilenet/network.py
- nnabla_nas/contrib/model.py
- nnabla_nas/module/module.py
- nnabla_nas/module/static/static_module.py
- nnabla_nas/runner/searcher/fairnas.py
- nnabla_nas/runner/searcher/search.py
- nnabla_nas/runner/trainer/train.py
- nnabla_nas/utils/cli/cli.py
1. arch.json was not created when --save-nnp option is used, so this PR fixes this issue
2. change output name is changed to y'.
3. add `--no-visualize` option to run in non-graphviz environment, and separate `visualize()` method from `save_parameters`.
> save arch.json when save-nnp option is specified.

- nnabla_nas/contrib/classification/darts/network.py
- nnabla_nas/module/module.py
- nnabla_nas/runner/searcher/fairnas.py
- nnabla_nas/runner/searcher/search.py
- nnabla_nas/runner/trainer/train.py
This PR supports that allows no_image_normalization parameters to be stored in nnp.
Here is the example:
```json
"hparams": {
"save_params": {
"no_image_normalization": true
}
}
```
This PR needs https://github.com/sony/nnabla/pull/1066
> add no_image_normalization param in executor when saving nnp

- nnabla_nas/dataset/csv.py
- nnabla_nas/utils/data/transforms.py
Introduce normalize and augment images provided by csv dataset.
Here is the example of json.
Currently, augmentation type can be selected from `imagenet` and `cifar10`.
```json
"dataloader": {
"csv": {
"train_portion": 0.96,
"train_file": "ilsvrc-train.csv",
"valid_file": "ilsvrc-test.csv",
"train_cache_dir": "ilsvrc-train.cache",
"valid_cache_dir": "ilsvrc-test.cache",
"augmentation": {
"type": "imagenet"
}
}
},
```
Also, `input_shapes` should be set actual input image size like `[3, 320, 320]` or `[3, 480,480]`.
> add image augmentation for csv dataloader

- nnabla_nas/contrib/classification/darts/network.py
There is issue introduced by https://github.com/sony/nnabla-nas/pull/16.
This PR fixes this issue in saving parameters for DARTS.
> fixed parameter save upon epoch end during search

- examples/classification/mobilenet/cifar10_search_latency.json
- examples/classification/mobilenet/imagenet_search_latency.json
- examples/classification/pnas/cifar10_search_latency.json
- nnabla_nas/runner/runner.py
- nnabla_nas/runner/searcher/pnas.py
- nnabla_nas/utils/cli/args.py
- nnabla_nas/utils/cli/cli.py
Regularizers (memory, latency, etc. ) were added to the optimizers dictionary. We separate them and add them to a new regularizer dictionary. This avoids some issues when saving checkpoints for auto-restart.
> get regulizers out of the optimizers dictionary.

- nnabla_nas/contrib/classification/ofa/elastic_modules.py
- nnabla_nas/contrib/classification/ofa/modules.py
- nnabla_nas/contrib/classification/ofa/network.py
By adopting this PR, the following issue will be solved.
Call print() will cause this error.
```python
model = algorithm.SearchNet(**attributes) if hparams['search'] else \
algorithm.TrainNet(**attributes)
print(model) # Adding this line
```
Execute this command.
```bash
python main.py \
-f examples/classification/ofa/ofa_imagenet_search_fullnet.json \
-a OFASearcher \
-o log/classification/ofa/imagenet/search/K7_E6_D4/
```
```
Traceback (most recent call last):
File "main.py", line 20, in <module>
main()
File "nnabla-nas/nnabla_nas/utils/cli/cli.py", line 102, in main
print(model)
File "nnabla-nas/nnabla_nas/module/module.py", line 592, in __str__
m_repr = str(module).split('\n')
File "nnabla-nas/nnabla_nas/module/module.py", line 589, in __str__
main_str = f'{self.__class__.__name__}(' …
```
> Add proper extra_repr to all OFA modules.

- nnabla_nas/module/module.py
- nnabla_nas/runner/searcher/ofa.py
This PR includes what I modified during a huddle session with @yuikosakuma1 to enable building a computation graph that doesn't require gradient computation in order to save memory for the intermediate variables. It is never tested but just committed at the end of the session. The changes include:
* Create computation graph with need_grad=False when `nnabla.no_grad()` is used or `self.need_grad=False` in Module class.
* Recursively change the following states in Module class: need_grad & training (I suppose this is the expected behavior. Otherwise, it'll ignore the specified states in submodules, which must be unexpected by users. For example, Dropout is applied even when you specify `model.training = False` where we suppose `model` is a top-level module containing Dropout class as a …
> Support nnabla.no_grad etc.

- nnabla_nas/contrib/classification/random_wired/random_wired.py
- nnabla_nas/contrib/classification/zoph/zoph.py
Scripts in examples/classification were not running due to some parameters not being inherited.
> Fix parameters not being  inherited.

- nnabla_nas/contrib/classification/ofa/networks/ofa_mbv3.py
- nnabla_nas/contrib/classification/ofa/networks/ofa_xception.py
- nnabla_nas/utils/estimator/estimator.py
CI did not pass after release of flake8 5.0
Flake8 returned several : E275 missing whitespace after keyword
This pull request fixes the formatting.
> Fix formating : missing whitespace after keyword

- nnabla_nas/runner/runner.py
Avoid the use of `print(f" {variable = } ...")` syntax that is not supported by Python < 3.8.
> f-string compatibility with Python version < 3.8

- nnabla_nas/contrib/classification/darts/modules.py
- tests/contrib/darts/__init__.py
- tests/contrib/darts/test_darts.py
Fix mismatching order of params of `class AvgPool`.
Related issue: #45
> Fix mismatching order of params of AvgPool

- nnabla_nas/contrib/classification/ofa/networks/ofa_resnet50.py
- nnabla_nas/contrib/classification/ofa/networks/ofa_xception.py
Adjust the working directories when reading the pretrained files since Hydra will change the working directories.
> Fix wrong working directory for OFAResnet50 and OFAXception search spaces

- conf/dataloader/classification/imagenet.yaml
- conf/dataloader/classification/imagenet_ofa.yaml
The directory name in dataset config is not consistent with that created by nnabla-example instruction (https://github.com/sony/nnabla-examples/tree/master/image-classification/imagenet#:~:text=Preparing%20ImageNet%20dataset)
For instance, the directory name is train/ and val/ by running the script in [the link](https://github.com/sony/nnabla-examples/tree/master/image-classification/imagenet#:~:text=Preparing%20ImageNet%20dataset), however, in NNablaNAS, the directory name is img_train and img_val.
> Fix imagenet datapath

- nnabla_nas/runner/searcher/ofa.py
OFA's test and validation loop was different which should be the same.
This bugfix unifies the test / valid loop in the `valid_genotype` function to avoid this bug and improve readability.
> Fix OFA valid/test

- nnabla_nas/utils/cli/args.py
Bug due to change for using global batch size.
`bz` parameter, that is used to calculate the number of iterations, should be the local batch size.
Because of this bug, LR scheduler did not calculate LR properly. (Estimates `batch_iters` smaller than the actual)
> Fix bz parameter for schedulers 

- .github/workflows/build.yml
- docs/requirements.txt
- setup.cfg
sklearn pakcage on PyPI is deprecating now, so we will migrate to use scikit-learn.
As references:
* https://pypi.org/project/sklearn/
* https://pypi.org/project/scikit-learn/
Also updated runtime environment because python3.6 environment is not available on ubuntu-latest.
> Use scikit-learn package instead of sklearn

- nnabla_nas/dataset/imagenet.py
This PR addresses issue #152 
Because of hydra, the ImageNet train/valid files are created in the hydra working directory (under log) for every experiment.
For instance, in this line;
https://github.com/nnabla/nnabla-nas/blob/61f2904f64a5744ad2bd58ff5cb46353bd498905/nnabla_nas/dataset/imagenet.py#L227-L231
This pressures memory, so we should create the file in the original working directory.
This PR changes the data file directory from `log/*` to the original working directory.
You can check this by running any experiment that uses ImageNet.
For example, run the follows:
```
python main.py experiment=classification/ofa/ofa_resnet50/imagenet_search_fullnet
```
And see  `__nnabla_nas__/imagenet_0.99` is created in the original working directory.
> Fix ImageNet data file directory 

- .readthedocs.yaml
Configuration file v2 (.readthedoc.yaml) is going to be mandatory on ReadTheDocs, here is the source: https://blog.readthedocs.com/migrate-configuration-v2/
This PR is the corresponding change to create documents by nnabla-nas/docs.
> Add .readthedocs.yaml v2

- docs/requirements.txt
This PR supports readthedocs configuration file format v2.
> Fix readthedocs dependency for version switch issue
